### ISSUE TITLE
AcrylicBrush with FindAncestor or similar

### ISSUE THREAD

**Issue by luetm** [sourcechord/FluentWPF#32]
Hi!

I would really like to use the AcrylicBrush for our project. We have a custom control, we call 'Panel' which has a header with a title and some content. We'd like to have that panel to have a blurred background, but since we use it everywhere we need the target to be dynamic.

What we would like is something like: 

`<Grid Background="{fw:AcrylicBrush Target={Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Window}}}" />`

Is that possible? Is the Target bindable?

**Comment by luetm** [comment]
Since the fw:AcrylicBrush is a MarkupExtension, we cannot bind unfortunately. I tried to wire up the acrylic brush to the panel in the code behind. Is there a way I can provide the Target was a FrameworkElement instead of a Name, so I can provide it directly? (I have a reference to the MainWindow, but it doesn't find it by name for some reason).

**Comment by luetm** [comment]
OK, I have something working, but it looks broken. I'm using an AcrylicPanel. Can you please explain, what exactly the properties **Source** and **Target** are actually used for?

**Comment by sourcechord** [comment]
Hi, @luetm.
Sorry for replying so late.

AcrylicBrush is MarkupExtension.
So that, AcrylicBrush's target property can't bind directry to another element as you said.

I think AcrylicPanel is maybe suitable for this case.
By the way, AcrylicBrush/AcrylicPanel is not support to use visual parent as Target property.
These class uses VisualBrush for rendering blur effect.
If you set visual parent element as Target property,
AcrylicBrush&AcrylicPanel's rendering process falls into infinite loop.
![image](https://user-images.githubusercontent.com/14825436/48145890-2deb6080-e2f7-11e8-8b6d-1db2dd9d7601.png)

You have to write AcrylicPanel on the layer that is not descendant of target property.

## OK
```cs
    <Grid>
        <Grid x:Name="grid" Background="White">
            <Image Margin="5"
                   Source="/FluentWPFSample;component/Assets/Images/1.jpg" />
        </Grid>
        <fw:AcrylicPanel Width="200" Height="200" HorizontalAlignment="Right"
                         Target="{Binding ElementName=grid}" />
    </Grid>
```

## NG
```cs
    <Grid>
        <Grid x:Name="grid" Background="White">
            <Image Margin="5"
                   Source="/FluentWPFSample;component/Assets/Images/1.jpg" />
            <fw:AcrylicPanel Width="200" Height="200" HorizontalAlignment="Right"
                         Target="{Binding ElementName=grid}" />
        </Grid>
    </Grid>
```

**Comment by luetm** [comment]
Thank you for the reply! That fixed it. Before, I had a ImageBrush as the background of the Window. Now I used an Image inside the window that renders behind everything else and manually wired that up to set it as the "Target" on the AcrilicPanel, and it works! Thank you!

So, what is the Source property on the Panel actually for?

**Comment by sourcechord** [comment]
I'm glad to hear that.

Source property is designed to be used for only internally.
This is not intended to be set by user.

I have come to think that the name of `Target` property is very confuseable.
These property name might be changed in future's update.
