### ISSUE TITLE
New window opens without content

### ISSUE THREAD

**Issue by Armin2208** [sourcechord/FluentWPF#49]
![image](https://user-images.githubusercontent.com/32982430/58372472-159f0400-7f1e-11e9-92a9-72034eb935d6.png)

Version: Windows 10 1903
UI appears after pressing Windows + Shift + S and leaving it.

Code:
DesktopBGui BGui = new DesktopBGui
            {
                Owner = GetWindow(this)
            };
            BGui.ShowDialog();

Opens just fine while running in visual studio debugging. But in the compiled release version outside of Visual Studio this happens.

**Comment by sourcechord** [comment]
Hi, @Armin2208.

Thanks for the feedback.
FluentWPF uses undocumented Win32API(SetWindowCompositionAttribute method).
This issue arises from the same causes as #42

SetWindowCompositionAttribute behavior is broken in Windows10 1903, so that I'm trying to avoid this behavior and support Windows10 1903.

Please wait for a while.

**Comment by sourcechord** [comment]
Hi, @Armin2208.
I fixed this issue, and released as FluentWPF 0.7.0.
Please, try it.

**Comment by Armin2208** [comment]
Problem is again present in Build 18363.418(+) - 1909.
