### ISSUE TITLE
Not able to change ShowTitleBar

### ISSUE THREAD

**Issue by gmangavin** [sourcechord/FluentWPF#52]
The only options I'm presented with are TilteBar and TitleBarMode.

TitleBar requires "" but does not support converting to string.

**Comment by vladimirantos** [comment]
I have the same problem. ShowTitleBas was not found in type AcrylicWindow.

**Comment by sourcechord** [comment]
Hi, @gmangavin @vladimirantos

This is by design, there is braking changes in FluentWPF 0.7.0.
ShowTitleBar was omitted.
Use AcrylicWindowStyle instead of ShowTitleBar property.
https://github.com/sourcechord/FluentWPF/releases/tag/v0.7.0

Sorry for lack of documentation.
I'll update README.md soon.

**Comment by noobhacker** [comment]
Request to close this issue since the document was fixed.
