### ISSUE TITLE
Glow window

### ISSUE THREAD

**Issue by YssStudios** [sourcechord/FluentWPF#89]
You should add the possibility of being able to take and manually configure the Glow Window

**Comment by sourcechord** [comment]
Hi @YssStudios 
Sorry for responding so late.
Fluent Design System doesn't have window's glow effect, so that I will not support it.
BTW I added [GitHub Discussions](https://github.com/sourcechord/FluentWPF/discussions) in this repository. Please create new discussions if you have any feature requests.
